# Generated by Django 4.2.5 on 2023-10-02 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_body2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body2',
        ),
    ]
